// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ticketremote_member_ticket_switch_type::TicketremoteMemberTicketSwitch;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ticketremote_member_ticket_switch`.
///
/// Obtain a handle from the [`TicketremoteMemberTicketSwitchTableAccess::ticketremote_member_ticket_switch`] method on [`super::RemoteTables`],
/// like `ctx.db.ticketremote_member_ticket_switch()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_ticket_switch().on_insert(...)`.
pub struct TicketremoteMemberTicketSwitchTableHandle<'ctx> {
    imp: __sdk::TableHandle<TicketremoteMemberTicketSwitch>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ticketremote_member_ticket_switch`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TicketremoteMemberTicketSwitchTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TicketremoteMemberTicketSwitchTableHandle`], which mediates access to the table `ticketremote_member_ticket_switch`.
    fn ticketremote_member_ticket_switch(&self) -> TicketremoteMemberTicketSwitchTableHandle<'_>;
}

impl TicketremoteMemberTicketSwitchTableAccess for super::RemoteTables {
    fn ticketremote_member_ticket_switch(&self) -> TicketremoteMemberTicketSwitchTableHandle<'_> {
        TicketremoteMemberTicketSwitchTableHandle {
            imp: self
                .imp
                .get_table::<TicketremoteMemberTicketSwitch>("ticketremote_member_ticket_switch"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TicketremoteMemberTicketSwitchInsertCallbackId(__sdk::CallbackId);
pub struct TicketremoteMemberTicketSwitchDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TicketremoteMemberTicketSwitchTableHandle<'ctx> {
    type Row = TicketremoteMemberTicketSwitch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TicketremoteMemberTicketSwitch> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TicketremoteMemberTicketSwitchInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberTicketSwitchInsertCallbackId {
        TicketremoteMemberTicketSwitchInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TicketremoteMemberTicketSwitchInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TicketremoteMemberTicketSwitchDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberTicketSwitchDeleteCallbackId {
        TicketremoteMemberTicketSwitchDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TicketremoteMemberTicketSwitchDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TicketremoteMemberTicketSwitchUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TicketremoteMemberTicketSwitchTableHandle<'ctx> {
    type UpdateCallbackId = TicketremoteMemberTicketSwitchUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TicketremoteMemberTicketSwitchUpdateCallbackId {
        TicketremoteMemberTicketSwitchUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TicketremoteMemberTicketSwitchUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `ticketremote_member_ticket_switch`,
/// which allows point queries on the field of the same name
/// via the [`TicketremoteMemberTicketSwitchIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ticketremote_member_ticket_switch().id().find(...)`.
pub struct TicketremoteMemberTicketSwitchIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TicketremoteMemberTicketSwitch, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TicketremoteMemberTicketSwitchTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `ticketremote_member_ticket_switch`.
    pub fn id(&self) -> TicketremoteMemberTicketSwitchIdUnique<'ctx> {
        TicketremoteMemberTicketSwitchIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TicketremoteMemberTicketSwitchIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<TicketremoteMemberTicketSwitch> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<TicketremoteMemberTicketSwitch>("ticketremote_member_ticket_switch");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TicketremoteMemberTicketSwitch>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<TicketremoteMemberTicketSwitch>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TicketremoteMemberTicketSwitch`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ticketremote_member_ticket_switchQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TicketremoteMemberTicketSwitch`.
    fn ticketremote_member_ticket_switch(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteMemberTicketSwitch>;
}

impl ticketremote_member_ticket_switchQueryTableAccess for __sdk::QueryTableAccessor {
    fn ticketremote_member_ticket_switch(
        &self,
    ) -> __sdk::__query_builder::Table<TicketremoteMemberTicketSwitch> {
        __sdk::__query_builder::Table::new("ticketremote_member_ticket_switch")
    }
}
