// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteMaintenance {
    pub ticket_id: String,
    pub paused: bool,
    pub updated_at: String,
}

impl __sdk::InModule for TicketremoteMaintenance {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteMaintenance`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteMaintenanceCols {
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteMaintenance, String>,
    pub paused: __sdk::__query_builder::Col<TicketremoteMaintenance, bool>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteMaintenance, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteMaintenance {
    type Cols = TicketremoteMaintenanceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteMaintenanceCols {
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteMaintenance`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteMaintenanceIxCols {
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteMaintenance, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteMaintenance {
    type IxCols = TicketremoteMaintenanceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteMaintenanceIxCols {
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteMaintenance {}
