// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteTicketActionV3 {
    pub id: String,
    pub action_id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub target: String,
    pub status: String,
    pub phase: String,
    pub current_view: String,
    pub switch_available: bool,
    pub switch_expires_at: String,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub reason: String,
    pub created_at: String,
    pub updated_at: String,
    pub completed_at: String,
    pub expires_at: String,
    pub parent_action_id: Option<String>,
    pub root_action_id: Option<String>,
    pub retry_ordinal: u32,
    pub terminal_fingerprint: Option<String>,
}

impl __sdk::InModule for TicketremoteTicketActionV3 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteTicketActionV3`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteTicketActionV3Cols {
    pub id: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub action_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub target: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub status: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub phase: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub current_view: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub switch_available: __sdk::__query_builder::Col<TicketremoteTicketActionV3, bool>,
    pub switch_expires_at: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub stream_epoch: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub frame_sequence: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub reason: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub created_at: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub completed_at: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteTicketActionV3, String>,
    pub parent_action_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3, Option<String>>,
    pub root_action_id: __sdk::__query_builder::Col<TicketremoteTicketActionV3, Option<String>>,
    pub retry_ordinal: __sdk::__query_builder::Col<TicketremoteTicketActionV3, u32>,
    pub terminal_fingerprint:
        __sdk::__query_builder::Col<TicketremoteTicketActionV3, Option<String>>,
}

impl __sdk::__query_builder::HasCols for TicketremoteTicketActionV3 {
    type Cols = TicketremoteTicketActionV3Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteTicketActionV3Cols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            action_id: __sdk::__query_builder::Col::new(table_name, "action_id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            target: __sdk::__query_builder::Col::new(table_name, "target"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            current_view: __sdk::__query_builder::Col::new(table_name, "current_view"),
            switch_available: __sdk::__query_builder::Col::new(table_name, "switch_available"),
            switch_expires_at: __sdk::__query_builder::Col::new(table_name, "switch_expires_at"),
            stream_epoch: __sdk::__query_builder::Col::new(table_name, "stream_epoch"),
            frame_sequence: __sdk::__query_builder::Col::new(table_name, "frame_sequence"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            parent_action_id: __sdk::__query_builder::Col::new(table_name, "parent_action_id"),
            root_action_id: __sdk::__query_builder::Col::new(table_name, "root_action_id"),
            retry_ordinal: __sdk::__query_builder::Col::new(table_name, "retry_ordinal"),
            terminal_fingerprint: __sdk::__query_builder::Col::new(
                table_name,
                "terminal_fingerprint",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteTicketActionV3`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteTicketActionV3IxCols {
    pub action_id: __sdk::__query_builder::IxCol<TicketremoteTicketActionV3, String>,
    pub backend_id: __sdk::__query_builder::IxCol<TicketremoteTicketActionV3, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteTicketActionV3, String>,
    pub status: __sdk::__query_builder::IxCol<TicketremoteTicketActionV3, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteTicketActionV3, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteTicketActionV3 {
    type IxCols = TicketremoteTicketActionV3IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteTicketActionV3IxCols {
            action_id: __sdk::__query_builder::IxCol::new(table_name, "action_id"),
            backend_id: __sdk::__query_builder::IxCol::new(table_name, "backend_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteTicketActionV3 {}
