// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteMemberConfirmControlCodeBrowserCaptureArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub session_id: String,
    pub request_id: String,
    pub candidate_frame_epoch: String,
    pub candidate_frame_sequence: String,
    pub marker_revision: String,
    pub accepted_reason: String,
}

impl From<TicketremoteMemberConfirmControlCodeBrowserCaptureArgs> for super::Reducer {
    fn from(args: TicketremoteMemberConfirmControlCodeBrowserCaptureArgs) -> Self {
        Self::TicketremoteMemberConfirmControlCodeBrowserCapture {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            session_id: args.session_id,
            request_id: args.request_id,
            candidate_frame_epoch: args.candidate_frame_epoch,
            candidate_frame_sequence: args.candidate_frame_sequence,
            marker_revision: args.marker_revision,
            accepted_reason: args.accepted_reason,
        }
    }
}

impl __sdk::InModule for TicketremoteMemberConfirmControlCodeBrowserCaptureArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_member_confirm_control_code_browser_capture`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_member_confirm_control_code_browser_capture {
    /// Request that the remote module invoke the reducer `ticketremote_member_confirm_control_code_browser_capture` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_member_confirm_control_code_browser_capture:ticketremote_member_confirm_control_code_browser_capture_then`] to run a callback after the reducer completes.
    fn ticketremote_member_confirm_control_code_browser_capture(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        candidate_frame_epoch: String,
        candidate_frame_sequence: String,
        marker_revision: String,
        accepted_reason: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_member_confirm_control_code_browser_capture_then(
            ticket_id,
            backend_id,
            session_id,
            request_id,
            candidate_frame_epoch,
            candidate_frame_sequence,
            marker_revision,
            accepted_reason,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_member_confirm_control_code_browser_capture` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_member_confirm_control_code_browser_capture_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        candidate_frame_epoch: String,
        candidate_frame_sequence: String,
        marker_revision: String,
        accepted_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_member_confirm_control_code_browser_capture for super::RemoteReducers {
    fn ticketremote_member_confirm_control_code_browser_capture_then(
        &self,
        ticket_id: String,
        backend_id: String,
        session_id: String,
        request_id: String,
        candidate_frame_epoch: String,
        candidate_frame_sequence: String,
        marker_revision: String,
        accepted_reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteMemberConfirmControlCodeBrowserCaptureArgs {
                ticket_id,
                backend_id,
                session_id,
                request_id,
                candidate_frame_epoch,
                candidate_frame_sequence,
                marker_revision,
                accepted_reason,
            },
            callback,
        )
    }
}
