// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteControlCodeRequest {
    pub id: String,
    pub ticket_id: String,
    pub owner_public_id: String,
    pub status: String,
    pub reason: String,
    pub message: String,
    pub requested_at: String,
    pub updated_at: String,
    pub result_expires_at: String,
    pub capture_required: bool,
    pub capture_acknowledged: bool,
    pub cleanup_pending: bool,
    pub stream_epoch: String,
    pub frame_sequence: String,
    pub min_frame_sequence: String,
    pub result_frame_epoch: String,
    pub result_min_frame_sequence: String,
    pub capture_frame_epoch: String,
    pub capture_frame_sequence: String,
    pub expires_at: String,
    pub result_proof: Option<String>,
    pub result_proof_at: Option<String>,
    pub result_marker_revision: Option<String>,
}

impl __sdk::InModule for TicketremoteControlCodeRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteControlCodeRequest`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteControlCodeRequestCols {
    pub id: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub owner_public_id: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub status: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub reason: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub message: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub requested_at: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub updated_at: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub result_expires_at: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub capture_required: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, bool>,
    pub capture_acknowledged: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, bool>,
    pub cleanup_pending: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, bool>,
    pub stream_epoch: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub frame_sequence: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub min_frame_sequence: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub result_frame_epoch: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub result_min_frame_sequence:
        __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub capture_frame_epoch: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub capture_frame_sequence: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, String>,
    pub result_proof: __sdk::__query_builder::Col<TicketremoteControlCodeRequest, Option<String>>,
    pub result_proof_at:
        __sdk::__query_builder::Col<TicketremoteControlCodeRequest, Option<String>>,
    pub result_marker_revision:
        __sdk::__query_builder::Col<TicketremoteControlCodeRequest, Option<String>>,
}

impl __sdk::__query_builder::HasCols for TicketremoteControlCodeRequest {
    type Cols = TicketremoteControlCodeRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteControlCodeRequestCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            owner_public_id: __sdk::__query_builder::Col::new(table_name, "owner_public_id"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            requested_at: __sdk::__query_builder::Col::new(table_name, "requested_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            result_expires_at: __sdk::__query_builder::Col::new(table_name, "result_expires_at"),
            capture_required: __sdk::__query_builder::Col::new(table_name, "capture_required"),
            capture_acknowledged: __sdk::__query_builder::Col::new(
                table_name,
                "capture_acknowledged",
            ),
            cleanup_pending: __sdk::__query_builder::Col::new(table_name, "cleanup_pending"),
            stream_epoch: __sdk::__query_builder::Col::new(table_name, "stream_epoch"),
            frame_sequence: __sdk::__query_builder::Col::new(table_name, "frame_sequence"),
            min_frame_sequence: __sdk::__query_builder::Col::new(table_name, "min_frame_sequence"),
            result_frame_epoch: __sdk::__query_builder::Col::new(table_name, "result_frame_epoch"),
            result_min_frame_sequence: __sdk::__query_builder::Col::new(
                table_name,
                "result_min_frame_sequence",
            ),
            capture_frame_epoch: __sdk::__query_builder::Col::new(
                table_name,
                "capture_frame_epoch",
            ),
            capture_frame_sequence: __sdk::__query_builder::Col::new(
                table_name,
                "capture_frame_sequence",
            ),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            result_proof: __sdk::__query_builder::Col::new(table_name, "result_proof"),
            result_proof_at: __sdk::__query_builder::Col::new(table_name, "result_proof_at"),
            result_marker_revision: __sdk::__query_builder::Col::new(
                table_name,
                "result_marker_revision",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `TicketremoteControlCodeRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct TicketremoteControlCodeRequestIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<TicketremoteControlCodeRequest, String>,
    pub id: __sdk::__query_builder::IxCol<TicketremoteControlCodeRequest, String>,
    pub owner_public_id: __sdk::__query_builder::IxCol<TicketremoteControlCodeRequest, String>,
    pub requested_at: __sdk::__query_builder::IxCol<TicketremoteControlCodeRequest, String>,
    pub status: __sdk::__query_builder::IxCol<TicketremoteControlCodeRequest, String>,
    pub ticket_id: __sdk::__query_builder::IxCol<TicketremoteControlCodeRequest, String>,
    pub updated_at: __sdk::__query_builder::IxCol<TicketremoteControlCodeRequest, String>,
}

impl __sdk::__query_builder::HasIxCols for TicketremoteControlCodeRequest {
    type IxCols = TicketremoteControlCodeRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TicketremoteControlCodeRequestIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner_public_id: __sdk::__query_builder::IxCol::new(table_name, "owner_public_id"),
            requested_at: __sdk::__query_builder::IxCol::new(table_name, "requested_at"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
            ticket_id: __sdk::__query_builder::IxCol::new(table_name, "ticket_id"),
            updated_at: __sdk::__query_builder::IxCol::new(table_name, "updated_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TicketremoteControlCodeRequest {}
