// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteBeginColdRestartArgs {
    pub ticket_id: String,
    pub backend_id: String,
    pub operation_id: String,
    pub actor_email: String,
}

impl From<TicketremoteBeginColdRestartArgs> for super::Reducer {
    fn from(args: TicketremoteBeginColdRestartArgs) -> Self {
        Self::TicketremoteBeginColdRestart {
            ticket_id: args.ticket_id,
            backend_id: args.backend_id,
            operation_id: args.operation_id,
            actor_email: args.actor_email,
        }
    }
}

impl __sdk::InModule for TicketremoteBeginColdRestartArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_begin_cold_restart`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_begin_cold_restart {
    /// Request that the remote module invoke the reducer `ticketremote_begin_cold_restart` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_begin_cold_restart:ticketremote_begin_cold_restart_then`] to run a callback after the reducer completes.
    fn ticketremote_begin_cold_restart(
        &self,
        ticket_id: String,
        backend_id: String,
        operation_id: String,
        actor_email: String,
    ) -> __sdk::Result<()> {
        self.ticketremote_begin_cold_restart_then(
            ticket_id,
            backend_id,
            operation_id,
            actor_email,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `ticketremote_begin_cold_restart` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_begin_cold_restart_then(
        &self,
        ticket_id: String,
        backend_id: String,
        operation_id: String,
        actor_email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_begin_cold_restart for super::RemoteReducers {
    fn ticketremote_begin_cold_restart_then(
        &self,
        ticket_id: String,
        backend_id: String,
        operation_id: String,
        actor_email: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteBeginColdRestartArgs {
                ticket_id,
                backend_id,
                operation_id,
                actor_email,
            },
            callback,
        )
    }
}
