// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TicketremoteOwnerSetMaintenanceArgs {
    pub ticket_id: String,
    pub paused: bool,
}

impl From<TicketremoteOwnerSetMaintenanceArgs> for super::Reducer {
    fn from(args: TicketremoteOwnerSetMaintenanceArgs) -> Self {
        Self::TicketremoteOwnerSetMaintenance {
            ticket_id: args.ticket_id,
            paused: args.paused,
        }
    }
}

impl __sdk::InModule for TicketremoteOwnerSetMaintenanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ticketremote_owner_set_maintenance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ticketremote_owner_set_maintenance {
    /// Request that the remote module invoke the reducer `ticketremote_owner_set_maintenance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ticketremote_owner_set_maintenance:ticketremote_owner_set_maintenance_then`] to run a callback after the reducer completes.
    fn ticketremote_owner_set_maintenance(
        &self,
        ticket_id: String,
        paused: bool,
    ) -> __sdk::Result<()> {
        self.ticketremote_owner_set_maintenance_then(ticket_id, paused, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ticketremote_owner_set_maintenance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ticketremote_owner_set_maintenance_then(
        &self,
        ticket_id: String,
        paused: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ticketremote_owner_set_maintenance for super::RemoteReducers {
    fn ticketremote_owner_set_maintenance_then(
        &self,
        ticket_id: String,
        paused: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TicketremoteOwnerSetMaintenanceArgs { ticket_id, paused },
            callback,
        )
    }
}
