// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TicketremoteMemberTicketSwitch {
    pub id: String,
    pub ticket_id: String,
    pub backend_id: String,
    pub current_view: String,
    pub expires_at: String,
}

impl __sdk::InModule for TicketremoteMemberTicketSwitch {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TicketremoteMemberTicketSwitch`.
///
/// Provides typed access to columns for query building.
pub struct TicketremoteMemberTicketSwitchCols {
    pub id: __sdk::__query_builder::Col<TicketremoteMemberTicketSwitch, String>,
    pub ticket_id: __sdk::__query_builder::Col<TicketremoteMemberTicketSwitch, String>,
    pub backend_id: __sdk::__query_builder::Col<TicketremoteMemberTicketSwitch, String>,
    pub current_view: __sdk::__query_builder::Col<TicketremoteMemberTicketSwitch, String>,
    pub expires_at: __sdk::__query_builder::Col<TicketremoteMemberTicketSwitch, String>,
}

impl __sdk::__query_builder::HasCols for TicketremoteMemberTicketSwitch {
    type Cols = TicketremoteMemberTicketSwitchCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TicketremoteMemberTicketSwitchCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ticket_id: __sdk::__query_builder::Col::new(table_name, "ticket_id"),
            backend_id: __sdk::__query_builder::Col::new(table_name, "backend_id"),
            current_view: __sdk::__query_builder::Col::new(table_name, "current_view"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}
